import express from "express";
import transactionController from "../Controller/transactionController.js";
import { isAuthenticated } from "../MiddleWares/Authentication.js";
const router = express.Router();
router.use(isAuthenticated);
router.get("/cart", transactionController.getCart);
router.get("/getAllCart", transactionController.getAllCart);
router.get("/addcart/:productCode", transactionController.addToCart);
router.delete("/cart/:id", transactionController.deleteCartItem);
export default router;
